import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { LayoutProvider } from "@/contexts/LayoutContext"; // Importando LayoutProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gpros - CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <LayoutProvider>{children}</LayoutProvider> {/* LayoutProvider agora envolve toda a aplicação */}
        </AuthProvider>
      </body>
    </html>
  );
}
